import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import { ReactNode } from 'react';
import { QueryProvider } from '@/providers/query-provider';
import { SheetProvider } from '@/providers/sheet-provider';
import { Toaster } from 'react-hot-toast';

const figtree = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={figtree.className}>
                    <QueryProvider>
                        <SheetProvider />
                        <Toaster
                            position="top-center"
                            reverseOrder={false}
                        />
                        {children}
                    </QueryProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
